### ISSUE TITLE
:propcheck stops the app from running - can we remove?

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [xou/elixlsx#141]
`:propcheck` stops the app from running - can we remove it?

**Comment by xou** [comment]
Hi Charles,
What's the error you're getting?

**Comment by allenwyma** [comment]
hi @xou i'm getting `** (Mix) Could not start application propcheck: could not find application file: propcheck.app`

**Comment by CharlesOkwuagwu** [comment]
same

**Comment by allenwyma** [comment]
hi @CharlesOkwuagwu and @xou checkout #142 as a workaround

**Comment by allenwyma** [comment]
hi @CharlesOkwuagwu maybe dont close this as my PR wasn't accepted 😄

**Comment by allenwyma** [comment]
hi @xou any updates on this?

**Comment by xou** [comment]
This should be fixed with the merge of #142 and release of 0.6.0. Let me know if you still have issues.
