### ISSUE TITLE
New release possible?

### ISSUE THREAD

**Issue by Miradorn** [xou/elixlsx#143]
Hi there and thanks for your work on this library!
Would it be possible to get a release? We currently have lots of warnings in our build logs due to the "old" String.slice syntax you already fixed upstream and we would love to upgrade to a new version.

Thanks again ❤️

**Comment by xou** [comment]
My apoligies, I find less time to work on this than I want to. This is an ongoing problem for me and I'm open to suggestions for long-term fixes :) Published version 0.6.0 now, let me know if you run into any problems.
