### ISSUE TITLE
Warning if sheet name is too long

### ISSUE THREAD

**Issue by kuon** [xou/elixlsx#28]
If I do

```elixir
    sheet = %Elixlsx.Sheet{name: "I am a very long sheet name sorry", rows: [[1,2],[1,2]]}
    workbook = %Elixlsx.Workbook{sheets: [sheet]}
    Elixlsx.write_to_memory(workbook, "#file.xlsx")
```

I got a warning when opening the file in excel (the Data is OK).

**Comment by Fabi755** [comment]
> I got a warning when opening the file in excel (the Data is OK).

We currently work at the bug with the warning message, see ticket #26.

Did this appear only on long sheet name? Which OS and version of excel you use?

**Comment by kuon** [comment]
Yeah, only on long sheet name. I use excel 365 on windows 10.

**Comment by xou** [comment]
Thanks @kuon for reporting this and @Fabi755 for the fix!
