### ISSUE TITLE
Missing newer release tags

### ISSUE THREAD

**Issue by bgentry** [xou/elixlsx#83]
Hi, thanks for writing/maintaining this library :v:

Could you please `git push --tags` when you have a chance so that the newer releases are tagged appropriately on GitHub? Thanks!

**Comment by xou** [comment]
I had actually forgotten to tag them in the first place. May need to invest in some kind of release automation at some point I guess...

I am not entirely sure where I cut the 0.4.0 ones; tagged the other commits at the point where I updated the mix.exs. Let me know if you run into problems & I will dig some more.

```
~/d/elixlsx ❯❯❯ git tag v0.4.1 fb7d5c2698052ce27c0e41405889d12251699234
~/d/elixlsx ❯❯❯ git tag v0.3.1 b6af0a00c8a66289861dbabdcb7913e9b9d1123c
~/d/elixlsx ❯❯❯ git push --tags
Total 0 (delta 0), reused 0 (delta 0)
To github.com:xou/elixlsx.git
 * [new tag]         v0.3.1 -> v0.3.1
 * [new tag]         v0.4.1 -> v0.4.1
```
