### ISSUE TITLE
If I pass nil into column parameter the lib broke

### ISSUE THREAD

**Issue by danielscosta** [xou/elixlsx#90]
This code:
`%Workbook{sheets: [%Sheet{name: "Posts", rows: [nil]}]}` breaks the lib when I execute `Elixlsx.write_to_memory("output.xlsx")` on Elixlsx.Compiler.compinfo_from_rows.
That's behaviour expected?

**Comment by unti1x** [comment]
Greetings. At first you didn't pass just a `nil`, it's a list with a single `nil` value. You should rather set `rows` to an empty list or not pass it it all. That's literally not a problem with the library. Maybe we could return an `:error` or throw some kind of exception to be clear but not more than this.

**Comment by danielscosta** [comment]
Thanks for the answer.

**Comment by unti1x** [comment]
You are welcome
