### ISSUE TITLE
Is it possible to modify existing file with this library?

### ISSUE THREAD

**Issue by tomekowal** [xou/elixlsx#96]
Hi!

I love how simple the API in this project is!

I can't find anything about reading xlsx file in the documentation. I am searching for something that can modify existing xlsx file. Is this possible?

Thanks for your amazing work!

**Comment by xou** [comment]
Hi! Unfortunately, this is not something that is supported. I briefly looked into this, for testing purposes for example, but opted not to proceed.

There's often more than one way of doing things in XLSX, and while as a 'writer' you can just pick one (well, one that works with the three/four large GUIs), as a 'reader' you need to support all the different ways of doing things (and combinations of those). I think this would lead down a rabbit hole that would introduce way more complexity into this library than I'd be comfortable with.

If someone wants to bridge elixlsx and an existing (or new) xlsx reader library, i'm not opposed to adding support code into this project, but I think the bulk of the parsing code should remain outside.
